using BogusLibrary.Generators;
using BogusLibrary.Models;

namespace BogusLibrary.Classes;

/// <summary>
/// Represents a singleton container for managing a collection of decimal values.
/// </summary>
/// <remarks>
/// The <see cref="Classes.DataContainer"/> class provides a thread-safe, lazily initialized singleton instance
/// that contains an array of decimal values. The values are generated using the <see cref="Generators.DecimalArrayGenerator"/>.
/// </remarks>
public sealed class DataContainer
{
    private static readonly Lazy<DataContainer> Lazy = new(() => new DataContainer());
    public static DataContainer Instance => Lazy.Value;

    /// <summary>
    /// Gets or sets the collection of decimal values managed by the <see cref="DataContainer"/>.
    /// </summary>
    /// <remarks>
    /// The decimal values are generated using the <see cref="Generators.DecimalArrayGenerator"/> 
    /// and are initialized with a range of 20 values between 1 and 1000.
    /// </remarks>
    public decimal[] Decimals { get; set; }

    /// <summary>
    /// Gets or sets the collection of human entities.
    /// </summary>
    /// <remarks>
    /// The <see cref="Humans"/> property contains a list of <see cref="BogusLibrary.Models.Human"/> objects.
    /// These objects are generated using the <see cref="BogusLibrary.Generators.HumanGenerator"/> class.
    /// </remarks>
    public List<Human> Humans { get; set; }

    /// <summary>
    /// Gets or sets the collection of products managed by the <see cref="DataContainer"/>.
    /// </summary>
    /// <remarks>
    /// Each product in the collection is represented by an instance of the <see cref="Products"/> class.
    /// The collection is initialized using the <see cref="Generators.ProductGenerator.Create(int, bool)"/> method.
    /// </remarks>
    public List<Products> Products { get; set; }
    
    /// <summary>
    /// Initializes a new instance of the <see cref="DataContainer"/> class.
    /// </summary>
    /// <remarks>
    /// This constructor is private to enforce the singleton pattern. It initializes the following properties:
    /// <list type="bullet">
    /// <item>
    /// <description><see cref="Decimals"/>: Populated with an array of decimal values generated by <see cref="DecimalArrayGenerator.GenerateRange"/>.</description>
    /// </item>
    /// <item>
    /// <description><see cref="Humans"/>: Populated with a list of <see cref="Human"/> objects generated by <see cref="HumanGenerator.Create"/>.</description>
    /// </item>
    /// <item>
    /// <description><see cref="Products"/>: Populated with a list of <see cref="Products"/> objects generated by <see cref="ProductGenerator.Create"/>.</description>
    /// </item>
    /// </list>
    /// </remarks>
    private DataContainer()
    {
        Decimals = DecimalArrayGenerator.GenerateRange(20, 1, 1000);
        Humans = HumanGenerator.Create(25);
        Products = ProductGenerator.Create(30);
    }
   
}